# Generated by Django 4.2.2 on 2023-06-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=20)),
                ("sms_count", models.IntegerField()),
                ("validity", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="recharge",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="recharge",
            name="modified_at",
        ),
        migrations.AddField(
            model_name="recharge",
            name="recharge_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
