# Generated by Django 4.2.2 on 2023-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_tariff_plan_alter_tariff_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tariff",
            name="plan",
            field=models.CharField(default="1000000", max_length=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="header",
            field=models.CharField(
                choices=[
                    ("Government", "Government"),
                    ("PSU", "PSU"),
                    ("Regular", "Regular"),
                    ("TRAI Exempted", "TRAI Exempted"),
                ],
                default="Regular",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="nature",
            field=models.CharField(
                choices=[("Promo", "Promo"), ("Trans", "Trans")],
                default="Trans",
                max_length=20,
            ),
        ),
    ]
