# Generated by Django 4.2.2 on 2023-07-05 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0004_alter_tariff_plan_alter_transaction_header_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pre_total_sms", models.IntegerField()),
                ("pre_used_sms", models.IntegerField()),
                ("pre_failed_sms", models.IntegerField()),
                ("forwarded_sms", models.IntegerField()),
                ("cur_total_sms", models.IntegerField()),
                ("cur_used_sms", models.IntegerField()),
                ("cur_failed_sms", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
