# Generated by Django 4.2.2 on 2023-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="rollback_sms",
            field=models.IntegerField(default=0),
        ),
    ]
