# Generated by Django 4.2.2 on 2023-07-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_message_rollback_sms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="forwarded_sms",
            field=models.IntegerField(default=0),
        ),
    ]
