# Generated by Django 4.2.2 on 2023-07-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_rollback"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollback",
            name="failed_sms_pct",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rollback",
            name="rb_from_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
