# Generated by Django 4.2.2 on 2023-07-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_rollback_failed_sms_pct_rollback_rb_from_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rollback",
            name="failed_sms_pct",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
