# Generated by Django 4.2.2 on 2023-06-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="system_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
