# Generated by Django 4.2.2 on 2023-07-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_system_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rollback_pct",
            field=models.IntegerField(default=16),
        ),
    ]
