# Generated by Django 4.2.2 on 2023-07-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_rollback_pct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="system_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
